---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
      threshold: "C"
ratings:
  paths:
    - "**.py"
exclude_paths:
  - hdlcc/tests/*
  - hdlcc/_version.py
  - versioneer.py
  - run_tests.py
